# /config/configuration.yaml

default_config:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

#notify:
#  - name: loadprofile
#    platform: file
#    filename: /config/loadprofile-1.csv
#    timestamp: true

#logger:
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug
#    custom_components.modbus.modbus: debug

homeassistant:

  customize: !include customize.yaml
  packages:
    tasmota1: !include pkg/tasmota1.yaml
    #modbus3: !include pkg/modbus3.yaml
    tasmota3: !include pkg/tasmota3.yaml
    testxxxxx: !include pkg/test.yaml
    #speedtest: !include pkg/speedtest.yaml
    utmxxxxxx: !include pkg/utm.yaml
    #modpollxx: !include pkg/modpoll.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 2
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_esp_clock
      - sensor.eb3_esp_clock
      - sensor.eb3_ha_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_0x*
      - sensor.eb1_clock*
      - sensor.eb3_clock*
###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

sensor integral: !include integral.yaml

###

sensor monitor:

  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use

###

###

climate:

  - platform: generic_thermostat
    name: Heat P1 7C
    heater: switch.athom_p1
    target_sensor: sensor.mho_7c_temp
    min_temp: 15
    max_temp: 21
    ac_mode: false
    target_temp: 18.5
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 2
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

  - platform: generic_thermostat
    name: Heat P1 GN
    heater: switch.athom_p1
    target_sensor: sensor.mmc_33_temp
    min_temp: 15
    max_temp: 21
    ac_mode: false
    target_temp: 18.5
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 2
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

###

sensor gps:

  - platform: template
    sensors:
      gps_accuracy:
        friendly_name: "GPS Accuracy"
        unit_of_measurement: "m"
        value_template: "{{ state_attr('device_tracker.s7', 'gps_accuracy') | int(0) }}"
        icon_template: "mdi:bullseye"

###

###
##
#

