# speedtest-cli ookla bin

sensor:

  - platform: command_line
    name: "ookla"
    command: "/config/apps/speedtest -f json --accept-license --accept-gdpr"
    scan_interval: 31
    value_template: "{{ value_json }}"

#eof

