# speedtest-cli ookla bin

sensor:

  - platform: command_line
    name: "Ookla Data"
    command: "/config/apps/speedtest -f json --accept-license --accept-gdpr"
    scan_interval: 31
    value_template: "{{ value_json.timestamp }}"
    json_attributes:
      - ping

#eof

