# speedtest-cli ookla bin

sensor:

  - platform: command_line
    name: "Ookla Data"
    command: "/config/apps/speedtest -f json --accept-license --accept-gdpr"
    scan_interval: 31
    value_template: >-
        {% set ping = value_json.ping.latency %}
        {{ ping }}
        

#eof

